Amazon_logo = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Email_field = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Continue_button = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Need_help_link = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Forgot_your_password_link = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Other_issues_with_Sign_In_link = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Create_your_Amazon_account_button = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Conditions of use link = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
Privacy_Notice_link = (By.XPATH, "//span[@class='nav-sprite nav-logo-base']")
HelpSearchField = (By.XPATH, "//input[@id='helpsearch']")
HelpSearcgButton = (By.XPATH, "//span[@id='helpSearchSubmit']")